export const caseStudiesContent = {
  title: 'Case Studies',
  subtitle: 'Real results from real projects',
  studies: [
    {
      id: 'agriculture-theni',
      title: 'Agriculture — Targeted Spraying, Theni',
      category: 'Agribot Spraying',
      location: 'Theni District, Tamil Nadu',
      summary: '50-acre cotton farm achieved 30% reduction in pesticide usage while improving coverage uniformity.',
      challenge: 'Manual spraying was inconsistent and labor-intensive, leading to pest resistance and chemical waste.',
      solution: 'Deployed agribot with GPS-guided variable rate application for precision targeting.',
      results: [
        '30% reduction in chemical usage',
        '25% faster application time',
        'Improved crop health and yield',
        'Zero operator chemical exposure',
      ],
      image: '/images/case-studies/agriculture-theni.jpg',
    },
    {
      id: 'solar-tirunelveli',
      title: 'Solar — Utility‑Scale, Tirunelveli',
      category: 'Drone Inspections',
      location: 'Tirunelveli District, Tamil Nadu',
      summary: '100MW solar plant inspection identified 47 critical hotspots, leading to 12% yield recovery.',
      challenge: 'Manual inspections were slow and missed hidden defects, causing ongoing performance losses.',
      solution: 'Thermal drone inspection with AI-assisted defect detection and priority classification.',
      results: [
        '47 critical hotspots identified',
        '12% energy yield recovery',
        'Inspection completed in 3 days vs. 2 weeks manual',
        'Detailed maintenance roadmap delivered',
      ],
      image: '/images/case-studies/solar-tirunelveli.jpg',
    },
    {
      id: 'construction-chengalpattu',
      title: 'Construction — Volumetrics, Chengalpattu',
      category: 'Aerial Mapping',
      location: 'Chengalpattu District, Tamil Nadu',
      summary: '25-acre construction site volumetric analysis delivered in 36 hours with 8mm accuracy.',
      challenge: 'Traditional surveying methods were too slow for weekly progress tracking needs.',
      solution: 'Weekly drone surveys with automated volumetric calculations and change detection.',
      results: [
        '36-hour turnaround time',
        '8mm accuracy achieved',
        'Weekly progress reports enabled',
        'Reduced surveying costs by 60%',
      ],
      image: '/images/case-studies/construction-chengalpattu.jpg',
    },
  ],
}
